name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/go4database.in/public_html/Go4Database

            git pull origin main

            pkill -f "uvicorn main:app" || true

            nohup /home/go4database.in/backend/venv/bin/uvicorn main:app \
            --host 127.0.0.1 \
            --port 8080 \
            --app-dir backend \
            > /home/go4database.in/logs/app.log 2>&1 &